IGDD-1765 Hub code to support Principals from Certs and JWTs.  Allows for optional mTLS.
IZGateway/izgw-hub pull request #23
Opened 2024-11-12 17:52 UTC by pcahillai

Introducing Principal classes to support certificates and JWT tokens.

pom.xml:
Specified specific version range for springdoc to fix problem with their release candidate build.

src/main/java/gov/cdc/izgateway/db/service/AccessControlService.java:
Code for getting the Principal from RequestContext and performing access control check using roles coming from a JWT token.

src/main/java/gov/cdc/izgateway/db/service/StatusCheckerService.java:
changing method to call setPrincipal instead of setCertificate

src/main/java/gov/cdc/izgateway/principal/provider/CertificatePrincipalProviderImpl.java:
The implementation of the Principal provider for Certificates.

src/main/java/gov/cdc/izgateway/principal/provider/JwtJwksPrincipalProvider.java:
The implementation of the Principal provider for JWTs used with JWKS.

src/main/java/gov/cdc/izgateway/principal/provider/JwtPrincipalProviderConfig.java:
Spring configuration to load the configured JwtPrincipal implementation.

src/main/java/gov/cdc/izgateway/principal/provider/JwtSharedSecretPrincipalProvider.java:
The implementation of the Principal provider for JWTs used with a shared secret.

src/main/java/gov/cdc/izgateway/principal/provider/RoleMapper.java:
Class that will support mapping scopes to roles.

src/main/java/gov/cdc/izgateway/principal/service/HubPrincipalService.java:
Implementation of the PrincipalService interface for Hub.

2024-11-13 18:46 UTC, keithboone commented on src/main/java/gov/cdc/izgateway/principal/provider/CertificatePrincipalProviderImpl.java
I think the izgw-hub/gov.cdc.izgateway.principal package belongs in izgw-core/gov.cdc.izgateway.security.principal

2024-11-13 18:46 UTC, keithboone commented on src/main/java/gov/cdc/izgateway/principal/provider/JwtJwksPrincipalProvider.java
I think the izgw-hub/gov.cdc.izgateway.principal package belongs in izgw-core/gov.cdc.izgateway.security.principal

2024-11-13 18:46 UTC, keithboone commented on src/main/java/gov/cdc/izgateway/principal/provider/JwtPrincipalProviderConfig.java
I think the izgw-hub/gov.cdc.izgateway.principal package belongs in izgw-core/gov.cdc.izgateway.security.principal

2024-11-13 18:47 UTC, keithboone commented on src/main/java/gov/cdc/izgateway/principal/provider/RoleMapper.java
I think the izgw-hub/gov.cdc.izgateway.principal package belongs in izgw-core/gov.cdc.izgateway.security.principal

2024-11-13 18:49 UTC, keithboone requested changes
I think the packaging needs work.  Most of the principal related stuff belongs to izgw-core, rather than izgw-hub.

The code isn't wrong, it's just in the wrong place to be taken advantage of by both hub and transform components.

2024-11-14 11:32 UTC, pcahillai commented on src/main/java/gov/cdc/izgateway/principal/provider/CertificatePrincipalProviderImpl.java
I made the recommended changes.

2024-11-14 11:32 UTC, pcahillai commented on src/main/java/gov/cdc/izgateway/principal/provider/JwtJwksPrincipalProvider.java
I made the recommended changes.

2024-11-14 11:33 UTC, pcahillai commented on src/main/java/gov/cdc/izgateway/principal/provider/JwtSharedSecretPrincipalProvider.java
I made the recommended changes.

2024-11-14 11:33 UTC, pcahillai commented on src/main/java/gov/cdc/izgateway/principal/provider/RoleMapper.java
I made the recommended changes.

2024-11-14 11:33 UTC, pcahillai commented on src/main/java/gov/cdc/izgateway/principal/service/HubPrincipalService.java
I made the recommended changes.

2024-11-25 19:20 UTC, closed without merging